security:
    encoders:
        # this internal class is used by Symfony to represent in-memory users
        Symfony\Component\Security\Core\User\User: 'bcrypt'

    providers:
        in_memory:
            memory:
                users:
                    admin: { password: '$2y$10$AmkVFNAqCmf1yOyBCglzPOrpEVsadbM684mikx1j8VVa7Z6tZbwDq', roles: ['ROLE_ADMIN'] }
                    mfteam: { password: '$2y$10$Xopp67LvIGDyCSRQDaI3CegqE/pC7zIMyYQzljBpIZSZXC9H9kc.S', roles: ['ROLE_ADMIN'] }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            form_login:
                login_path: auth_login
                check_path: login
                csrf_token_generator: security.csrf.token_manager
                default_target_path: /admin
            logout:
                path: /logout
                target: /auth/login
            remember_me:
                secret:   '%env(APP_SECRET)%'
                lifetime: 2520000 # 30 days in seconds
                path:     /

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
