version: '3'
services:
    mysql:
        image: mysql:5.7
        container_name: ${APPLICATION_NAME}_mysql
        volumes:
            - "./.data/db:/var/lib/mysql"
            - "./mysql/my.cnf:/etc/mysql/my.cnf"
        ports:
            - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        command: "--default-authentication-plugin=mysql_native_password"
        networks:
            - 'application'
    php:
        build: php-fpm
        container_name: ${APPLICATION_NAME}_php
        ports:
            - '9000:9000'
        volumes:
            - ../:/var/www/symfony:delegated
            - ./logs/symfony:/var/www/symfony/var/log:delegated
        links:
            - mysql
        depends_on:
            - mysql
        networks:
            - 'application'
    nginx:
        build: nginx
        container_name: ${APPLICATION_NAME}_nginx
        env_file:
            - './.env'
        ports:
            - '${APPLICATION_DEFAULT_PORT}:80'
            - '${APPLICATION_SSL_PORT}:443'
        links:
            - php
        volumes:
            - './../:/var/www/symfony:delegated'
            - './logs/nginx/:/var/log/nginx:delegated'
        networks:
          - 'application'

networks:
    application:
        external:
            name: ${APPLICATION_NAME}
